### ISSUE TITLE
HDTV no terminal output

### ISSUE THREAD

**Issue by jupalmes** [janmayer/hdtv#33] opened 2023-11-23 22:25 UTC
I just installed hdtv for the first time and it launches as expected, I can naviagte in the terminal, load spectra, which show up in the graphics interface, and I can mark boundaries and I can fit with the results showing up in the GUI, but nothing shows up in the terminal. I ran the installation process on different devices and tried different methods for installing root, but always got the same issue. Any help would be appreciated.

**Comment by op3** [comment] 2023-11-25 13:44
What is your operating system, python version (e.g., run `python --version`) and prompt_toolkit version (e.g., run `python -c "import prompt_toolkit; print(prompt_toolkit.__version__)"`)?

**Comment by antosaracino** [comment] 2024-01-01 22:07
Hi, I have exactly the same issue described above. I am running on Ubuntu 22.04.3 LTS, with ROOT 6.28.10 (but I also tried previous releases). My python version is 3.10.12 and prompt_toolkit version is 3.0.43. Could you help me please?

**Comment by janmayer** [comment] 2024-01-02 20:20
I could reproduce the issue - in [`SimpleUI print`](https://github.com/janmayer/hdtv/blob/11c0dc54bb8d1f3b4422cd9c16bd31032739700d/hdtv/ui.py#L64), the event loop is not running when call_soon_threadsafe is called (or at least something like that).

```python
        hdtv.cmdline.command_line.loop.call_soon_threadsafe(
            self.print_patched, HTML(html), end
        )
```

Im not sure what the loop is for - I see only few usages. The commented out `self.print_patched(HTML(html), end)` seems to work.

@op3, do you remember the specifics of [Add support for prompt_toolkit 3.0 (asyncio)](https://github.com/janmayer/hdtv/commit/e4d18cadbb860a6b9590c87e572c7fdb903caa23)

**Comment by antosaracino** [comment] 2024-01-03 18:59
Thanks! Indeed commenting out that line, everything seems to work.

**Comment by op3** [comment] 2024-01-15 08:54
I have not managed to reproduce this exact issue yet. However, I can trigger the same behavior by entering and exiting a python shell in hdtv (execute `python` inside hdtv and then `exit()` it again) (thanks to @j-kleemann for noticing this).

I think I had similar problems (no output) when I ported the code to prompt_toolkit 3.0 in e4d18cadbb860a6b9590c87e572c7fdb903caa23 before introducing `call_soon_threadsafe`, but I don’t remember the specifics.

**Comment by op3** [comment] 2024-01-15 22:16
The problem should be fixed now. Printing also works after entering and leaving an ipython shell inside hdtv.

When closing hdtv using the close button of the graphical window, we have to make sure that the event loop is stopped before ROOT exits. For this, we need an event loop that can be addressed. Because the behavior of prompt_toolkit changed, this event loop was never started. We now manually create a dedicated thread to run the event loop. Printing works, and exiting hdtv both from the terminal and the GUI works (without segfaulting).

**Closed by op3** 2024-01-15 22:16 UTC
